name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build EXE
        run: dotnet publish VideoPlayer.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: VideoPlayer-Windows
          path: publish/
